---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nac-platform.fullname" . }}-secrets
  labels:
    {{- include "nac-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.commonEnv.JWT_SECRET | quote }}
  {{- if .Values.aaa.enabled }}
  radius-secret: {{ .Values.aaa.env.RADIUS_SECRET | quote }}
  {{- end }}
